### ISSUE TITLE
求助：表示克隆下来代码之后，运行cherub命令行不同

### ISSUE THREAD

**Issue by nongxi** [l-zhi/marrycard#1]
环境：npm6.3.0+winodws10
1.环境npm已经安装并配置，但是运行不起来，显示cherub命令不存在；
2.尝试以pyrhon自带服务器启动发现图片为分层显示，也没有h5婚礼请柬的效果；

**Comment by l-zhi** [comment]
> 环境：npm6.3.0+winodws10
> 1.环境npm已经安装并配置，但是运行不起来，显示cherub命令不存在；
> 2.尝试以pyrhon自带服务器启动发现图片为分层显示，也没有h5婚礼请柬的效果；

应该是安装失败了，我readme上安装的命令写错了少写了个npm，用这个 `sudo npm install -g cherub`， 如果安装比较慢可以尝试用淘宝的镜像地址安装，会快点。

**Comment by nongxi** [comment]
ok，好的，我切换一下安装源
